name: Deploy Backend API

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "dtms-webapp"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.404"
          
      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install dependencies
        run: dotnet restore ${{ github.workspace }}/DTMS_BE.sln

      - name: Apply EF Core Migrations
        run: dotnet ef database update --project ./Repositories --startup-project ./DTMS_API
        env:
          ASPNETCORE_ENVIRONMENT: Production
          ConnectionStrings__DtmsDB: ${{ secrets.DATABASE_CONNECTION_STRING }}

      - name: Build
        run: dotnet build ${{ github.workspace }}/DTMS_BE.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ github.workspace }}/DTMS_BE.sln --configuration Release --output ${{ github.workspace }}/publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ${{ github.workspace }}/publish
